version: "3"

tasks:
  test:
    method: none
    sources: ["*/go.mod"]
    cmds:
      - for: sources
        task: test-dir
        vars: {DIR: "{{dir .ITEM}}"}

  test-dir:
    label: "test {{.DIR}}"
    dir: "{{.DIR}}"
    cmd: go test
    sources:
      - "*.go"

  lint:
    method: none
    sources: ["*/go.mod"]
    cmds:
      - for: sources
        task: lint-dir
        vars: {DIR: "{{dir .ITEM}}"}

  lint-dir:
    label: "lint {{.DIR}}"
    dir: "{{.DIR}}"
    cmd: golangci-lint run
    sources:
      - "*.go"

  format:
    deps:
      - format:go
      - format:mise
      - format:yaml

  format:go:
    method: none
    sources: ["*/go.mod"]
    cmds:
      - for: sources
        task: format:go-dir
        vars: {DIR: "{{dir .ITEM}}"}

  format:go-dir:
    label: "format {{.DIR}}"
    dir: "{{.DIR}}"
    cmd: golangci-lint fmt --enable=gofumpt
    sources:
      - "*.go"

  format:mise:
    desc: format mise config
    cmd: mise fmt
    sources:
      - mise.toml

  format:yaml:
    desc: format yaml
    cmd: yamlfmt -formatter indent=2,retain_line_breaks=true ./**/*.yaml ./.github/**/*.yaml
    sources:
      - ./**/*.yaml
      - ./.github/**/*.yaml

  ci:
    cmds:
      - task: format
      - task: lint
      - task: test
