name: commit

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .task
          key: ${{ runner.os }}-go-task
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - run: task ci
